<?php

declare(strict_types=1);

namespace App\Handlers\Commands\Users;

use App\Contracts\CommandHandler;
use App\Enums\UserState;
use App\Handlers\BaseHandler;
use App\Models\User;
use App\Support\Result;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Override;
use RuntimeException;

/**
 * Register User Command Handler.
 *
 * Handles user registration using the monadic CQRS pattern.
 * Migrated from App\Actions\Users\RegisterUser.
 */
final class RegisterUserHandler extends BaseHandler implements CommandHandler
{
    /**
     * Handle the RegisterUser command.
     *
     * @param  RegisterUserCommand  $command  The command to handle
     */
    #[Override]
    public function handle(object $command): Result
    {
        if (! $command instanceof RegisterUserCommand) {
            return Result::failure('Invalid command type', ['Expected RegisterUserCommand']);
        }

        /** @return Result<User> */
        return Result::try(
            fn (): User => DB::transaction(fn (): User => $this->registerUser($command)),
            ['Starting user registration']
        )->flatMap(fn (mixed $user): Result => $this->setBioIfProvided($user instanceof User ? $user : throw new RuntimeException('Invalid user type'), $command));
    }

    /**
     * Register a new user.
     */
    private function registerUser(RegisterUserCommand $command): User
    {
        // ULID is auto-generated by HasUlid trait
        return User::query()->create([
            'name' => $command->data['name'],
            'email' => $command->data['email'],
            'password' => Hash::make((string) $command->data['password']),
            'state' => $command->data['state'] ?? UserState::PENDING,
            'tenant_id' => $command->data['tenant_id'] ?? null,
        ]);
    }

    /**
     * Set bio if provided in the command data.
     */
    private function setBioIfProvided(User $user, RegisterUserCommand $command): Result
    {
        if (! isset($command->data['bio'])) {
            return Result::success($user->fresh(), ['User registered without bio']);
        }

        $locale = app()->getLocale();
        $user->setTranslation('bio', $locale, $command->data['bio']);
        $user->save();

        $fresh = $user->fresh();
        throw_unless($fresh instanceof User, RuntimeException::class, 'User not found after bio update');

        return Result::success($fresh, ['User registered with bio']);
    }
}
