<?php

declare(strict_types=1);

namespace App\Actions\Users;

use App\Enums\UserState;
use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Spatie\QueueableAction\QueueableAction;

final class RegisterUser
{
    use QueueableAction;

    /**
     * Register a new user with explicit transaction control.
     *
     * @param  array<string, mixed>  $data
     */
    public function handle(array $data): User
    {
        return DB::transaction(function () use ($data): User {
            $user = User::query()->create([
                'name' => $data['name'],
                'email' => $data['email'],
                'password' => Hash::make($data['password']),
                'state' => $data['state'] ?? UserState::PENDING,
                'tenant_id' => $data['tenant_id'] ?? null,
            ]);

            // ULID is auto-generated by HasUlid trait
            // Bio can be set via translatable attributes if provided
            if (isset($data['bio'])) {
                $locale = app()->getLocale();
                $user->setTranslation('bio', $locale, $data['bio']);
                $user->save();
            }

            return $user->fresh();
        });
    }
}
